name: Create and publish gem

on:
  workflow_dispatch:

jobs:
  cross-compile:
    strategy:
      matrix:
        platform:
          - "x64-mingw32"
          - "x86-mingw32"
          - "x64-mingw-ucrt"
    name: Cross-compile gem
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/rake-compiler/rake-compiler-dock-image:1.3.0-mri-${{ matrix.platform }}"

    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/tiny_tds/tiny_tds # shrug
      - name: Install gems
        shell: bash
        run: bundle install
      - name: Write used versions into file
        shell: bash
        run: bundle exec rake ports:version_file[${{ matrix.platform }}]
      - name: Cache ports
        uses: actions/cache@v3
        with:
          path: ports
          key: cross-compiled-v2-${{ hashFiles('**/.ports_versions') }}
          restore-keys: |
            cross-compiled-${{ hashFiles('**/.ports_versions') }}
            cross-compiled-v2-
      - name: Build gem
        shell: bash
        run: bundle exec rake gem:for_platform[${{ matrix.platform }}]
      - name: Move gems into separate directory before persisting
        run: |
          mkdir -p artifacts/gem
          mv pkg/*.gem artifacts/gem
      - uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
          path: artifacts/gem

  publish:
    needs: cross-compile
    name: Publish Gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build regular gem
        run: bundle exec rake gem

      - name: Download precompiled gems
        uses: actions/download-artifact@v3

      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: Token ${CLOUDSMITH_API_KEY}\n" > $HOME/.gem/credentials
        env:
          CLOUDSMITH_API_KEY: ${{secrets.CLOUDSMITH_API_KEY}}

      - name: Push Gems to Cloudsmith
        run: |
          VERSION=$(cat VERSION)
          export RUBYGEMS_HOST=https://ruby.cloudsmith.io/simplificator/public
          gem push pkg/tiny_tds-$VERSION.gem
          gem push gem-x64-mingw32/tiny_tds-$VERSION-x64-mingw32.gem
          gem push gem-x64-mingw-ucrt/tiny_tds-$VERSION-x64-mingw-ucrt.gem
          gem push gem-x86-mingw32/tiny_tds-$VERSION-x86-mingw32.gem
